name: AutoServerRestart
main: ZtechNetwork\Minecraft\AutoServerRestart\Loader
version: 3.0.0-beta1
api: [1.12.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7]
load: STARTUP
author: ZtechNetwork
description: Restarts your server at given interval.
website: https://github.com/LeronDoesGM
commands:
 asr:
  description: "Set ASR Time"
  permission: asr.command.asr
 restart:
  description: "Check ASR Status"
  permission: asr.command.restart
permissions:
 asr.command.asr:
  description: "Usage: /asr <value>"
  default: op
 asr.command.restart:
  description: "Usage: /restart"
  default: true
